name: search
version: 0.2.1
description:
  A small search engine middleware for 'package:database'. Meant for applications that want to do
  basic searches without an external search engine like ElasticSearch/Lucene.
homepage: https://github.com/dint-dev/database

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  charcode: ^1.1.0
  database: ^0.2.3
  meta: ^1.1.0

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.8.0

dependency_overrides:
  database:
    path: '../database'