name: database_adapter_azure
version: 0.0.1
description: An adapter for using 'package:database' with MySQL / MariaDB.
homepage: https://github.com/dint-dev/database

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  database: ^0.3.0
  fixnum: ^0.10.0
  universal_io: '>=0.8.5 <2.0.0'

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.8.0
  test_io: ^0.1.0

dependency_overrides:
  database:
    path: '../../database'