name: database
version: 0.3.3
description:
  A database access API that's vendor-agnostic. Adapters exist for browser APIs, SQLite, Google
  Cloud Firestore, PostgreSQL, ElasticSearch, Algolia, and others.
homepage: https://github.com/dint-dev/database

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  built_collection: ^4.0.0
  built_value: '>=5.0.0 <8.0.0'
  charcode: ^1.1.0
  collection: ^1.14.0
  fixnum: ^0.10.0
  meta: ^1.1.0
  protobuf: '>=0.13.0 <2.0.0'
  universal_html: ^1.1.0
  universal_io: '>=0.8.6 <2.0.0'

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.8.0